---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.5.5
    chart: aws-load-balancer-controller
    helm:
      values: |
        clusterName: eks-argocd
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
